export default {
    name: 'Besh',
    level: 3,
    ancestry: 'Wellspring Gnome',
    class: 'Leaf Druid',
    background: 'Battle Medic',
    size: 'Small',
    alignment: 'CG',
    deity: 'Desna',
    ethnicity: '',
    nationality: '',
    birthplace: '',
    age: '',
    gender: 'Female',
    height: '',
    weight: '',
    appearance: '',
    attitude: '',
    beliefs: '',
    likes: '',
    dislikes: '',
    catchphrases: '',
    notes: '',
};